### ISSUE TITLE
HTTP_1_1_REQUIRED

### ISSUE THREAD

**Issue by sbabiv** [mhewedy/ews#3]
NTLM: true
err: Post https://mail.domain.ru/ews/Services.wsdl: stream error: stream ID 3; HTTP_1_1_REQUIRED

**Comment by mhewedy** [comment]
sorry for the late response, I just noticed the issue...

I am trying to duplicate the issue, but it seems this domain is not accessible (I tried 2 internet providers).

Can you provide the IP address of the domain so I can investigate the issue?

**Comment by sbabiv** [comment]
I am connecting to a server (ms exchange 2016 CU15) on the local network
Looks like a problem with go-ntlmssp
The problem is solved by setting GODEBUG = http2client = 0 # disable HTTP / 2 client support
go version go1.13.1 darwin / amd64

https://golang.org/pkg/net/http/

ntlm authorization works using http1.1 protocol

**Comment by mhewedy** [comment]
Thanks for the update

**Comment by sbabiv** [comment]
**This code solves the problem**
TLSNextProto: map[string]func(authority string, c *tls.Conn) http.RoundTripper{},

```go
&http.Client{
			Timeout: timeout,
			Transport: ntlmssp.Negotiator{
				RoundTripper: &http.Transport{
					TLSNextProto: map[string]func(authority string, c *tls.Conn) http.RoundTripper{},
				},
			},
```
