### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by yalva** [mhewedy/ews#4]
I'm trying to send an email with the example in readme, and its throwing 401 Unauthorized error, I've tested the same URL and credentials with nodejs ews and it works. any idea?

**Comment by knochms** [comment]
Me too...
I think there is a problem with the _ntlmssp.Negotiator{}_ (from: https://github.com/Azure/go-ntlmssp).

`Response:
HTTP/1.1 401 Unauthorized
Content-Length: 0
Date: Fri, 19 Jun 2020 10:15:23 GMT+3
Request-Id: 7***********************9
Server: Microsoft-IIS/8.5
Set-Cookie: ClientId=IZ********OP; expires=Sat, 19-Jun-2021 10:15:24 GMT+3; path=/; HttpOnly
Www-Authenticate: Negotiate
Www-Authenticate: NTLM
X-Feserver: ***
X-Powered-By: ASP.NET

----
401 Unauthorized
`

Any ideas?

**Comment by mhewedy** [comment]
Sorry for late reply.

if you are using an on-premises Exchange server (or even if you manage your servers at the cloud), you need to pass the username as `AD_DOMAINNAME\\username` instead, for examle `MYCOMANY\\mhewedy`.

**Comment by mhewedy** [comment]
I will close this as resolved. feel free to reopen if you face the suggested solution didn't fix your issue.
